### ISSUE TITLE
Version your imports

### ISSUE THREAD

**Issue by ebebbington** [eveningkid/denodb#171]
I notice some of your imports always use the latest version on Deno.land, and others actually use the master branch on github - there is a high chance this is going to break users’ code and should be avoided at all costs

I’d actually avoid the use of denodb until this has been addressed, and it’s unknown whether issues have been created for your repo just because someone pushed a bug to their master branch

**Comment by eveningkid** [comment]
Hey Edward,

First of all, it is totally fine if you decide not to use denodb.

I do not have enough time to work on this library, and so it goes for bumping dependencies.

If there is an issue coming from another library, I also believe that they will quickly work on it.
If it happens to be a major bug, enough people will either help on that other repo or do it here.

This is not as perfect as I wish it would be, but one thing about open source is that this is time I give away.
I wish there would be more people trying to help, instead of taking the time to tell me how things should be.

You are a developer as much as I am, so you can help if you think it should be improved.
That is the main reason this is open-sourced, so people like you can help

**Comment by ebebbington** [comment]
The main problem is, if there is an issue with with another library ie in their master branch, then every user that uses denodb at that time will fail to run their app

I did make the issue without a PR because I don’t have time to work on other projects, although today is an exception so I’ll work on a PR in 10 mins

**Comment by eveningkid** [comment]
Hey,

Just a quick update: the remaining dependencies have been versioned.

Thanks Edward for raising this issue.

Good day
