### ISSUE TITLE
Uncaught (in promise) AssertionError at WireProtocol

### ISSUE THREAD

**Issue by gabeklavans** [eveningkid/denodb#180]
I will  always get the following error either right when I start my server or after a couple of requests to the API, with no code changing in between restarts:

```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:152:11)
    at WireProtocol.receive (protocol.ts:80:7)
```

Kinda tough to debug this since it gives such limited information and happens seemingly randomly.

I presume it has something to do with the mongo library being used under the hood, since I found multiple references to WireProtocol in the mongo third party package for Deno, but I have not tried to debug this further due to my limited knowledge. It might be solely a problem with the underlying library or with how DenoDB is interacting with it.

Here is some relevant initialization code from my program:
```
const app = opine();

app.use(opineCors());

/* DB */
const connector = new MongoDBConnector({
  uri: "mongodb://127.0.0.1:27017",
  database: "lc-test",
});

const db = new Database(connector);

db.link([User, Wallet]);

db.sync({
  drop: true,
});

...

const PORT = 5000;

// Simple log requests
app.use((req, res, next) => {
  console.log(`${req.method}: ${req.path}`);
  next();
});

app.use("/api", router).listen({ port: PORT });
```

[and the full code base if you're curious](https://github.com/SuGar33-Coding/leetcoin)

**Comment by eveningkid** [comment]
Hey Gabriel,

I feel very sorry for not answering you earlier, my apologies.

Although it seems you've since moved your leetcoin project to Node, I'll still give you an answer.

There were [similar issues I found on deno_mongo](https://github.com/denodrivers/deno_mongo/issues/182), that seemed to have been fixed now. However, concurrent queries still [seem to be a problem at times](https://github.com/denodrivers/deno_mongo/issues/189). Unfortunately it really seems to be related to deno_mongo here since denodb is only a wrapper and has no influence on this.

I have upgraded the mongodb driver to its latest version which I hope can fix the issue.

Best of luck with crypto, to the moon :)

Have a great day
