### ISSUE TITLE
Property 'query' does not exist on type 'Client'

### ISSUE THREAD

**Issue by Foxford13** [eveningkid/denodb#202]
Heya, me again. Did a reload of modules on deno as ive been having some issues with some of them and i started getting this error
```
error: TS2339 [ERROR]: Property 'query' does not exist on type 'Client'.
        await this._client.query("SELECT 1 + 1 as result")
                           ~~~~~
    at https://deno.land/x/denodb@v1.0.21/lib/connectors/postgres-connector.ts:51:28

TS2339 [ERROR]: Property 'query' does not exist on type 'Client'.
    const response = await this._client.query(query);
                                        ~~~~~
    at https://deno.land/x/denodb@v1.0.21/lib/connectors/postgres-connector.ts:63:41

Found 2 errors.
```
I havnt changed my code and the only thing i did was the '--reload' flag when i run my app.
The annoying part was that I dont even use postgres for my app and making the whole experience even more so confusing.

EDIT:
Ok, just realised that the version indicated in the error is 1.0.21 whereas newest release is 1.0.23, will look into that.
EDIT2: Yeah, no matter what i do and how i try to force the version it keeps popping up with that error.

**Comment by Aiko-Suzuki** [comment]
Got the same errors
https://prnt.sc/107lksw

**Comment by eveningkid** [comment]
Hey,

Are you still experiencing this issue?

I believe this was because dependencies were not versioned which led to changes in the postgres driver API breaking denodb.

For various reasons, the driver should soon be upgraded to its latest version and its denodb connector counterpart too.

Just need to know if using denodb@master is still raising this issue :)

Thanks for helping really, and sorry for the long wait.

Good day

**Comment by eveningkid** [comment]
I believe this issue is no longer so I'll close this for now. 

If you're still experiencing it, really feel free to reopen and I'll be happy to help :)
