### ISSUE TITLE
Deno DB Transaction

### ISSUE THREAD

**Issue by duqrlgkdntm9** [eveningkid/denodb#204]
Hello
Deno DB is in use.
Is there any way to use Transaction in Deno DB?
My DB = MariaDB

I'm sorry I didn't write that long.
My English is poor. 
Thanks

**Comment by eveningkid** [comment]
Hey,

Great question.

Our [MySQL connector has support for transactions](https://github.com/eveningkid/denodb/blob/master/lib/connectors/mysql-connector.ts#L81-L97) actually but since other databases don't, it isn't in use.

So it would be possible but this needs more time to be implemented.

If I see more support for transactions, I'll happily spend time on this improvement.
To anyone reading this, feel free to comment below even if the issue is closed for now.

Good day :)

**Comment by eveningkid** [comment]
Actually, just found out that someone asked for these too on MySQL.

I'll see how this can be added as a MySQL-only for now.

**Comment by eveningkid** [comment]
Hey,

Transactions have been added for most db engines (except MongoDB)!

You can now upgrade to the latest version to start using them.

You'll find an [example in the PR](https://github.com/eveningkid/denodb/pull/237) and more information [in the documentation](http://eveningkid.com/denodb-docs/docs/guides/transactions).

Have a great day :)
