### ISSUE TITLE
Bump Deno SQLite version to 2.0.0

### ISSUE THREAD

**Issue by dyedgreen** [eveningkid/denodb#24]
Please consider upgrading the SQLite version, see https://github.com/dyedgreen/deno-sqlite/releases

The new version now automatically commits changes to databases to the file-system, and generally is more in-line with how a natively compiled SQLite3 package would function 😃

**Comment by eveningkid** [comment]
Hey Tilman, how are you :)

Thanks for reaching out, you are right about this.

I believe the only place denodb is using your library is [in this file](https://github.com/eveningkid/denodb/blob/master/lib/connectors/sqlite3-connector.ts).

Do you see any breaking change besides `open` and `save`?

**Comment by dyedgreen** [comment]
Thanks for the swift response! No the only breaking change is the removal of `open`, `close`, and `data` functions. So the upgrade should be very straight forward (replace `await open(file)` with `new DB(file)`, and remove any calls to `save(...)`.

Do you want me to open a PR to update the dependency?

**Comment by eveningkid** [comment]
Thanks for the details, I quickly upgraded that's alright!

I had forgotten to set the version specifically so it then even caused an issue (#25) which is why I wanted to solve this quickly.

Next time would be great of course if you want to contribute :)

Thanks for your efforts on that library, it's working well with denodb!

See you around
