### ISSUE TITLE
The system cannot find the path specified. (os error 3)

### ISSUE THREAD

**Issue by kitchanismo** [eveningkid/denodb#32]
>deno version 1.0.5
>windows 10
>mysql 10.4.11

**Comment by eveningkid** [comment]
Hey Cristian,

Not so sure what might be the issue as you don't provide any reproducible code.

However, [Deno MySQL](https://github.com/manyuanrong/deno_mysql) does not support the recent versions of MySQL.
**It apparently only supports 5.5.**

I would suggest you to either use a PostgreSQL or SQLite database which both work fine in any case.

If you encounter any other issue, feel free to reopen an issue (this time with more information so that I can help you better :)).
