### ISSUE TITLE
Edge case with field name case conversion

### ISSUE THREAD

**Issue by Coteh** [eveningkid/denodb#43]
If I have a field named `flightID` for example, it's returned from DB as `flightId`:
```
import { DataTypes, Database, Model } from "https://deno.land/x/denodb/mod.ts";

const db = new Database("sqlite3", {
  filepath: "temp.db",
});

class Flight extends Model {
  static table = "flights";
  static timestamps = true;

  static fields = {
    flightID: {
      primaryKey: true,
      autoIncrement: true,
    },
    departure: DataTypes.STRING,
  };
}

db.link([Flight]);

await db.sync({ drop: true });

await Flight.create([
  {
    departure: "Paris",
  },
  {
    departure: "London",
  },
]);

console.log(await Flight.all());
```
Output
```
[
  {
      flightId: 1,
      departure: "Paris",
      createdAt: "2020-06-06 15:03:54",
      updatedAt: "2020-06-06 15:03:54"
    },
  {
      flightId: 2,
      departure: "London",
      createdAt: "2020-06-06 15:03:54",
      updatedAt: "2020-06-06 15:03:54"
    }
]
```

**Comment by Coteh** [comment]
I think `flightId` is the conventional way of putting it in PascalCase/camelCase. I usually write 'id' part all caps, just a habit of mine. Perhaps there should be a note in the docs about this? Not sure if it's worth patching this one edge case. What do you think?

**Comment by eveningkid** [comment]
It's fair, and I think in the long term, the implementation should be different.

Right now it is formatted by default. However I think it would be better to have something like that instead:

```javascript
// In Model, computed and based on `static fields`
fieldNames = {
  // [Original field name (from client side)]: database field name,
  flightId: 'flight_id',
};
```

This would then allow to override default formatting field names, just as in your case.

Right now, the original field name is lost in translation...as it expects your field name to follow naming conventions. **But yes, it might create some confusion in case the name is different.**

So two options:
- I can add a comment about this in the documentation
- We can add this now in the code

I just feel a little tired right now, working on this every day. I need a break. So this might have to wait unless you want to work on it, but no pressure.

**Comment by Coteh** [comment]
Actually, wouldn’t mind taking a stab at it! :)

We can have the field name be automatically converted by default (as it currently does) but the `fieldNames` property can be provided to `Model` if you want to override any of them, like what you showed above. What do you think?

On Jun 6, 2020, at 1:02 PM, Arnaud Dellinger <notifications@github.com<mailto:notifications@github.com>> wrote:


It's fair, and I think in the long term, the implementation should be different.

Right now it is formatted by default. However I think it would be better to have something like that instead:

// In Model, computed and based on `static fields`
fieldNames = {
  // [Original field name (from client side)]: database field name,
  flightId: 'flight_id',
};

This would then allow to override default formatting field names, just as in your case.

Right now, the original field name is lost in translation...as it expects your field name to follow naming conventions. But yes, it might create some confusion in case the name is different.

So two options:

  *   I can add a comment about this in the documentation
  *   We can add this now in the code

I just feel a little tired right now, working on this every day. I need a break. So this might have to wait unless you want to work on it, but no pressure.

**Comment by eveningkid** [comment]
*Alright so I warn you, this is a long message coming in!*

> We can have the field name be automatically converted by default (as it currently does) but the `fieldNames` property can be provided to `Model` if you want to override any of them, like what you showed above. What do you think?

Yes, I think we should first think in terms of use cases. From what I can think of:

1) I already have a database and want to match an existing field name, but want the returned name to be what I've decided (`flightID` below):
```javascript
static fields = {
  flightID: {
    type: DataTypes.INTEGER,
    as: 'flight_weird_id',
  },
};

await Flight.insert({ flightID: 1 });
// Should map `flightID` to `flight_weird_id` when added to the database

const flight = await Flight.find(1);
console.log(flight.flightID);
// Should map `flight_weird_id` to `flightID`
```
By default, `flightID` should be accessible as such from the client and be `flight_id` in the database if `as` is not provided.

2) I don't have a database and want to name my fields the way I want (which was your intention at first)
```javascript
static fields = {
  flightID: DataTypes.INTEGER,
};
```
As explained earlier, this should map to `flight_id` in the database and be translated back when we get `flight_id` from the database.

Sorry, I didn't want to make this too long but I hope you can see what we should be able to do with this feature:
- name any fieldname we want (`flightID`) and format them using pascal case in the database but still get them as we named it in the first place
- override the default fieldname formatting and use the `as` field descriptor instead if provided

I think instead of having another property in `Model` from the user side, we should compute a naming table, based on `fields`. If you check `Model`'s code, you will see `findPrimaryKey()` or something similar. We could compute a table used internally for matching names:

```javascript
// You can change the name, I just thought of that...
_fieldMatching = {
  // Case using `as`
  flightID: 'flight_weird_id',

  // Default behavior
  userName: 'user_name',
}
```

You would then need to refer to that table when creating fields in the database, and when queries are being made.

This is how I see it, with the current structure of the code. I think it's great as we would only compute this table on initialisation, then no extra formatting would be needed.

If you have another suggestion, you're very welcome to share it!
Otherwise, I think we can go with that :)

Keep in touch James, and thanks again for your time. I really appreciate it

**Comment by eveningkid** [comment]
James, in case you ever see this, I will take over as it's been raised by another issue.
I bet you're just busy so no worries :)

**Comment by Coteh** [comment]
Hey man that’s no problem, so sorry I didn’t get back! I wanted to get around to this at some point but was wrapped up in other projects. What you proposed was a good solution!

On Jun 15, 2020, at 8:02 AM, Arnaud Dellinger <notifications@github.com<mailto:notifications@github.com>> wrote:


James, in case you ever see this, I will take over as it's been raised by another issue.
I bet you're just busy so no worries :)
