### ISSUE TITLE
Camel Case Column

### ISSUE THREAD

**Issue by krisanalfa** [eveningkid/denodb#51]
Hi, I'm working with existing database with camel case column. Apparently, this library tends to convert the field name into snake case. How can I use custom naming for certain column? Something like:

```ts
export class City extends Model {
  public static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    state: DataTypes.INTEGER,
    name: DataTypes.STRING,
    zipCodeRange: {
      field: "customZipCodeRange", // force query to use this column name instead of `zip_code_range`
      type: DataTypes.STRING,
    },
    lat: DataTypes.FLOAT,
    lng: DataTypes.FLOAT,
  };
}
```

Thanks!

**Comment by eveningkid** [comment]
Hey Krisan :)

Thanks a lot for your feedback, it is actually on its way following #43. I was waiting on a contributor but I will take this on.

The original behaviour was to follow "SQL naming conventions" but it then turned out to give no power on overriding this.

I will update this issue as soon as this gets updated.

Keep in touch, it won't take long :)

**Comment by eveningkid** [comment]
Hello again!

It's been merged, so the way to do it for your example is the following:
```typescript
export class City extends Model {
  public static fields = {
    // ...
    zipCodeRange: {
      as: "customZipCodeRange",
      type: DataTypes.STRING,
    },
  };
}
```

Remember to run deno using `deno run --reload ...`.

Have a good day :)
