### ISSUE TITLE
Permissions and default download of deno_mongo.dll

### ISSUE THREAD

**Issue by SquareMesh** [eveningkid/denodb#54]
Added to project for use against mysql database

export const db = new Database('mysql', {
  database: config.DB,
  host: config.DB_URI,
  username: config.DB_USER,
  password: config.DB_PASSWORD,
  port: 3306, // optional
});

deno run failed with error 'Deno.openPlugin' is an unstable API

deno run requires the following permissions
--unstable
--allow-write=.deno_plugins

Is this correct? (readme doesn't mention)

Once running app started downloading deno_mongo.dll, this was surpise as mysql was specified as the database.

Is this a bug?  Downloading mongo plugin when not required.
Does denodb download other plugins dynamically? i.e. mysql 

Haven't progressed further as deno requires now --allow-plugin.

Ideally would want to use denodb without providing additional parameters - other than allow-net

**Comment by eveningkid** [comment]
Hey,

Thanks a lot for raising this question, you're right about this.

So basically, after introducing Mongo in denodb, it turned out that we would always need to add `--unstable` and others.

I will have a look at it and see if this could only be called when using Mongo and still keeping the codebase consistant.

I will get back to you very soon!

Keep in touch

**Comment by SquareMesh** [comment]
No worries, thanks for the update.

**Comment by eveningkid** [comment]
Alright so a quick update: I rearranged the code for this to be working the way you would expect, e.g. we now only need `` to use mysql.

The problem is: `deno_mongo` cannot be lazy-loaded correctly, which creates all sorts of problem at the moment ([I just asked them if they could do something about it](https://github.com/manyuanrong/deno_mongo/issues/55)).

So until they get back to me, we will have to wait. I found a solution, could just make a fork and use that fork instead of their github but this is just not a good solution right now.

Unless they can't figure something out, we will do it "the dirty way" then.

Just be patient then, I will update this issue whenever I hear back from them :)

**Comment by SquareMesh** [comment]
Thanks for the quick update :)

I'm just getting started in the deno / javascript / typescript arena.  But in looking to be helpful I came across a reference to dynamic loading of modules.  Maybe helpful to you.  No rush happy for progress to happen as it does.

https://stackoverflow.com/questions/13444064/typescript-conditional-module-import-export

async function importModule(moduleName):Promise<any>{
    console.log("importing ", moduleName);
    const importedModule = await import(moduleName);
    console.log("\timported ...");
    return importedModule;
}

let moduleName:string = "module-a";
importModule(moduleName)
.then(importedModule => {
    console.log("importedModule");
});

**Comment by eveningkid** [comment]
Exactly, this is what I have done actually and it works fine. I explained the issue better on their repo: they have an `await init(...)` statement which needs to be "done" before using the library. However, when using `await import(...)` it does not wait on it, and raises an error!

I don't think it is good practice to have an `await` statement in your main file. It should be an additional function that initialises the library, but for now that's all we have.

This is why I said we can only wait or make a fork which isn't ideal at the moment :D

**Comment by eveningkid** [comment]
Alright, #57 should have fixed it!

I decided to go with the fork option as it doesn't seem to be changing on the other repo.

You should just use `deno run --reload ...` to make sure you get the updated version!

Reopen the issue if it's not working but I guess it should :)

Take care

**Comment by SquareMesh** [comment]
Hi @eveningkid 

Thanks for your work on this, it worked a treat. The whole downloading a DLL and --unstable options didn't sit well against the appeal of security within Deno.
