### ISSUE TITLE
Connection Mongodb

### ISSUE THREAD

**Issue by nestorPons** [eveningkid/denodb#60]
deno run --allow-net --allow-read --allow-write --unstable app.ts

only show :
INFO load deno plugin "deno_mongo" from local "/home/nestor/http/DB/.deno_plugins/deno_mongo_2970fbc7cebff869aa12ecd5b8a1e7e4.so"
Segment violation (generated core)

regards

**Comment by eveningkid** [comment]
Hello Nestor,

Thanks for sharing this issue.

Well, it seems to be an issue with the plugin initialisation, not denodb itself.

Could you try [the deno_mongo readme example](https://github.com/manyuanrong/deno_mongo#examples) first and let me know if that runs well on your end?

If it doesn't, then the issue comes from their side and should be asked on their repo.

Keep in touch

**Comment by eveningkid** [comment]
Hey Nestor,

If I don't get any answer from you, I believe your issue has been solved.

I will give this another day before closing it otherwise as this seems related to your configuration more than denodb itself.

Let me know

**Comment by nestorPons** [comment]
Hi I'm sorry the wait was offline over the weekend
I tried it with the example and it doesn't work either, I get the same error.

deno 1.0.2 <-- now i think that's the problem

i have the same error in another repository ,  which tries to make a connection with mongo:
Trobyss/deno-api-rest-jwt

sorry for the inconvenience
regards

**Comment by eveningkid** [comment]
Thanks for the update Nestor :)

No worries, I just try to keep track of the issues.

Maybe you should just try to upgrade your deno version with `deno upgrade`.

Have a good day!

**Comment by nestorPons** [comment]
Sorry one question:
what line 43 does, is the one that gives me panic
