### ISSUE TITLE
Query with where returns all records when where condition is undefined 

### ISSUE THREAD

**Issue by FottyM** [eveningkid/denodb#70]
So I was testing the `ORM` and I have to say that I really appreciate the simplicity of it and it is really appreciated.
My issue is more of a question than a bug that I am trying to file.

I have this table in my database called languages and I want to query a certain language by iso code.
When I hardcode the value I want, in this case, `fr`, this is what I get:

```typescript
 await Language.select("isoCode").where("isoCode", "fr").first();
```
```
{
   schema: [Function: Language],
   select: [ "iso_code" ],
   wheres: [ { field: "iso_code", operator: "=", value: "fr" } ],
   limit: 1,
   table: "languages",
   type: "select"
 }
```
and that generates this SQL query:
```sql
select 1;
select "iso_code" from "languages" where "iso_code" = 'fr' limit 1
```
However, when I try to pass the iso code dynamically and in my case it, was undefined

```typescript
await Language.select("isoCode").where("isoCode", isoCode).first(); // note isoCode is undefined
```

As we can see below it ignores the `where` filter and just does the select part of the query. Because here I have the limit set to one with `.first()` function call otherwise, it returns all the records.

```
{
   schema: [Function: Language],
   select: [ "iso_code" ],
   limit: 1,
   table: "languages",
   type: "select"
 }
```

```sql
 select 1;
 select "iso_code" from "languages" limit 1;
```

So is this intended of it's a bug?

Edit:
I am using Postgres

**Comment by FottyM** [comment]
I found the [line](https://github.com/eveningkid/denodb/blob/057ddfaed4268a17d128130bd957df09f5290dd7/lib/model.ts#L393) that is causing is it. It just skips `undefined` 🤔.
```typescript
for (const [field, value] of Object.entries(fieldOrFields)) {
        if (value === undefined) {
          continue;
        }

```

**Comment by eveningkid** [comment]
Hey Fortunat,

Sorry it took me awhile to get back to you!

I can finally say "it is a feature" because it is indeed intended behaviour.

Just ask yourself: "is it worth making a SQL query if no iso code is provided?"

In your case, I think the best option would be to check for `isoCode` being `undefined` and if it is, not making the query. I don't know exactly what is your use case here, but I believe you don't want to query anything if it is `undefined`.

Even from a developer perspective, if `isoCode` could be `undefined`, it should appear in your code because this is not very common.

I hope my explanation makes sense to you. If it doesn't, please do not hesitate to let me know!

Have a great day
