### ISSUE TITLE
Modeling of foreign keys

### ISSUE THREAD

**Issue by halvardssm** [eveningkid/denodb#9]
Hi! I'm intrigued about your module! Just wondering: how should I go about adding foreign keys to a model?

**Comment by eveningkid** [comment]
Hey Halvard,

There is no foreign key system at the moment, simply because I am still thinking about the best API to do this if I'm honest! :)

They still can be "faked" at the moment, e.g. `airport_id` in a `Flight` model then combined with `Airport.find(flight.airport_id)`.

If you have any suggestion on how you would see that API, you're more than welcome to share it here.

It quickly becomes something big as it would need to handle relationships in general. My way-to-go is usually to look at Laravel Eloquent API which I always find great, but what's your take? :)

**Comment by halvardssm** [comment]
Hi Arnaud,

I think following the Laravel API is a good solution since it covers pretty much everything, it is also my go-to whenever I wonder about something DB specific.

I'll think about it a bit more, and I'll let you know if I have any revelations 😊

**Comment by eveningkid** [comment]
It is all now possible with denodb.

More information can be found in the [README](https://github.com/eveningkid/denodb#relationships) :)
